services:
  laravel_franken:
    container_name: laravel_franken
    image: laravel-orbstack/mariadb
    # image: laravel-orbstack/mysql
    # image: laravel-orbstack/postgres
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
      # dockerfile: docker/mysql/Dockerfile
      # dockerfile: docker/postgres/Dockerfile
    ports:
      - "8001:80"
    env_file:
      - .env
    depends_on:
      - mariadb
      # - mysql
      # - postgres
      - redis

  # MariaDB
  mariadb:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: laravel
      MARIADB_USER: laravel
      MARIADB_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  # MySQL
  # mysql:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: laravel
  #     MYSQL_PASSWORD: secret
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # MariaDB & MySQL
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    depends_on:
      - mariadb
      # - msyql
      #

  # PostgreSQL
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: laravel
  #     POSTGRES_USER: laravel
  #     POSTGRES_PASSWORD: secret
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # # PostgreSQL
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: secret
  #   depends_on:
  #     - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    depends_on:
      - mariadb
      # - mysql
      # - postgres

volumes:
  mariadb_data:
  # mysql_data:
  # postgres_data:
  redis_data:
